#!/bin/sh -e

gitdir=$(git rev-parse --git-dir)

trap "rm -f /tmp/tags.$$" EXIT

ctags --tag-relative -R -f /tmp/tags.$$ --exclude=$gitdir \
    --languages=-javascript,sql

mv /tmp/tags.$$ $gitdir/tags
